### PR TITLE
Finished api

### PR DESCRIPTION
**Pull request by softwareengineering2019**

### CODE REVIEW

**Comment by katunold** [comment]
good work Eng. builds are passing and maitainability is excellent. Please try to make your readme file descriptive

**Comment by softwareengineering2019** [comment]
> good work Eng. builds are passing and maitainability is excellent. Please try to make your readme file descriptive

Thanks very much Anold

**Comment by walimike** [comment]
Hey this is dop, well done, just a pointer you to consider  when assigning an incremental id dependant on the length of a list(order list), this format can have issues in case one of the elements is deleted, because a new item would then get a similar id as the element[-1] on the list, this in itself is a bug, so moving forward you should look into that

**Comment by softwareengineering2019** [comment]
> Hey this is dop, well done, just a pointer you to consider when assigning an incremental id dependant on the length of a list(order list), this format can have issues in case one of the elements is deleted, because a new item would then get a similar id as the element[-1] on the list, this in itself is a bug, so moving forward you should look into that

Thank you very much for the comment but i think what i have done is fine at the moment since am not using a database. Remember were are storing data in data structures so it is difficult to track what you are saying. But i think when we implement this using a database , then your argument stands. But when we are using data structures we can only keep track of the id by incrementing depending on the size of the list. Thank you very much.

**Comment by Luleherll** [comment]
looks fine. you can add a `.gitignore` to ignore the cache stuff

**Comment by softwareengineering2019** [comment]
> looks fine. you can add a `.gitignore` to ignore the cache stuff

Thank you very much

**Comment by walimike** [comment]
> > Hey this is dop, well done, just a pointer you to consider when assigning an incremental id dependant on the length of a list(order list), this format can have issues in case one of the elements is deleted, because a new item would then get a similar id as the element[-1] on the list, this in itself is a bug, so moving forward you should look into that
> 
> Thank you very much for the comment but i think what i have done is fine at the moment since am not using a database. Remember were are storing data in data structures so it is difficult to track what you are saying. But i think when we implement this using a database , then your argument stands. But when we are using data structures we can only keep track of the id by incrementing depending on the size of the list. Thank you very much.

`orderlist = [{'id':1,...},{'id':2,...},{'id':3,..}]` if you delete `id=2`, at that point, len of list is 2, now if you add an item, using this logic:` id = len(orderlis)+1` it will tale 3 as its id meaning you'll have 2 elements with the sameid, does that make sense?

**Comment by softwareengineering2019** [comment]
> > > Hey this is dop, well done, just a pointer you to consider when assigning an incremental id dependant on the length of a list(order list), this format can have issues in case one of the elements is deleted, because a new item would then get a similar id as the element[-1] on the list, this in itself is a bug, so moving forward you should look into that
> > 
> > 
> > Thank you very much for the comment but i think what i have done is fine at the moment since am not using a database. Remember were are storing data in data structures so it is difficult to track what you are saying. But i think when we implement this using a database , then your argument stands. But when we are using data structures we can only keep track of the id by incrementing depending on the size of the list. Thank you very much.
> 
> `orderlist = [{'id':1,...},{'id':2,...},{'id':3,..}]` if you delete `id=2`, at that point, len of list is 2, now if you add an item, using this logic:`id = len(orderlis)+1` it will tale 3 as its id meaning you'll have 2 elements with the sameid, does that make sense?

Yah i understand mike but the fact is when you delete an item in the list, say you have deleted an item with id 2, so the next item with id 3 will occupy the space that item 2 had previously and it will take on id 2. So its imposible for an item to have the same id. But thanks for the comments.

**Pull request closed without merging**
